### ISSUE TITLE
Missing Import in PiBeam.py

### ISSUE THREAD

**Issue by jlandgrave62** [sbcshop/PiBeam_Software#1]
When I try to load one of the sample projects and I add PiBeam.py I get the following error:

Import "st7789" could not be resolved

This import is on line 8 of the PiBeam.py code and, in fact, there is no "st7789" file anywhere in the sample code.

**Comment by sbcshop3** [comment]
Please use firmware provided on github: https://github.com/sbcshop/PiBeam_Software/blob/main/PiBeam_firmware.uf2 
This firmware has inbuilt st7789 library module.
